echo ":::::::::::::::::::::::::::::::::"
echo ":::::::::::::::::::::::::::::::::"
echo ":::::         Aine          :::::"
echo ":::::                       :::::"
echo ":::::   :::::      :::::    :::::"
echo ":::::   :::::      :::::    :::::"
echo ":::::                       :::::"
echo ":::::     ::::::::::::      :::::"
echo ":::::     ::::::::::::      :::::"
echo ":::::                       :::::"
echo ":::::::::::::::::::::::::::::::::"
echo ":::::::::::::::::::::::::::::::::"
echo "[*] JANGAN DISHARE, DI SHARE REPO INI AKAN DI HAPUS !!"
echo "[*] Made by Muhammad Ridwan Reynaldy"
echo "[*] All dependencies have been installed, please run the command \"npm start\" to immediately start the script"
npm start